// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIServerSettingsService creates a new instance of MockIServerSettingsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServerSettingsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServerSettingsService {
	mock := &MockIServerSettingsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServerSettingsService is an autogenerated mock type for the IServerSettingsService type
type MockIServerSettingsService struct {
	mock.Mock
}

type MockIServerSettingsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServerSettingsService) EXPECT() *MockIServerSettingsService_Expecter {
	return &MockIServerSettingsService_Expecter{mock: &_m.Mock}
}

// GetExarotonAPIKey provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) GetExarotonAPIKey(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExarotonAPIKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServerSettingsService_GetExarotonAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExarotonAPIKey'
type MockIServerSettingsService_GetExarotonAPIKey_Call struct {
	*mock.Call
}

// GetExarotonAPIKey is a helper method to define mock.On call
//   - ctx
func (_e *MockIServerSettingsService_Expecter) GetExarotonAPIKey(ctx interface{}) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	return &MockIServerSettingsService_GetExarotonAPIKey_Call{Call: _e.mock.On("GetExarotonAPIKey", ctx)}
}

func (_c *MockIServerSettingsService_GetExarotonAPIKey_Call) Run(run func(ctx context.Context)) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIServerSettingsService_GetExarotonAPIKey_Call) Return(s string, err error) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIServerSettingsService_GetExarotonAPIKey_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExarotonAPIKey provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) UpdateExarotonAPIKey(ctx context.Context, apiKey string) error {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExarotonAPIKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServerSettingsService_UpdateExarotonAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExarotonAPIKey'
type MockIServerSettingsService_UpdateExarotonAPIKey_Call struct {
	*mock.Call
}

// UpdateExarotonAPIKey is a helper method to define mock.On call
//   - ctx
//   - apiKey
func (_e *MockIServerSettingsService_Expecter) UpdateExarotonAPIKey(ctx interface{}, apiKey interface{}) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	return &MockIServerSettingsService_UpdateExarotonAPIKey_Call{Call: _e.mock.On("UpdateExarotonAPIKey", ctx, apiKey)}
}

func (_c *MockIServerSettingsService_UpdateExarotonAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIServerSettingsService_UpdateExarotonAPIKey_Call) Return(err error) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServerSettingsService_UpdateExarotonAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) error) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	_c.Call.Return(run)
	return _c
}
