// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"exaroton-wa-bot/internal/dto"
	"exaroton-wa-bot/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIServerSettingsService creates a new instance of MockIServerSettingsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServerSettingsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServerSettingsService {
	mock := &MockIServerSettingsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServerSettingsService is an autogenerated mock type for the IServerSettingsService type
type MockIServerSettingsService struct {
	mock.Mock
}

type MockIServerSettingsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServerSettingsService) EXPECT() *MockIServerSettingsService_Expecter {
	return &MockIServerSettingsService_Expecter{mock: &_m.Mock}
}

// GetExarotonAPIKey provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) GetExarotonAPIKey(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExarotonAPIKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServerSettingsService_GetExarotonAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExarotonAPIKey'
type MockIServerSettingsService_GetExarotonAPIKey_Call struct {
	*mock.Call
}

// GetExarotonAPIKey is a helper method to define mock.On call
//   - ctx
func (_e *MockIServerSettingsService_Expecter) GetExarotonAPIKey(ctx interface{}) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	return &MockIServerSettingsService_GetExarotonAPIKey_Call{Call: _e.mock.On("GetExarotonAPIKey", ctx)}
}

func (_c *MockIServerSettingsService_GetExarotonAPIKey_Call) Run(run func(ctx context.Context)) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIServerSettingsService_GetExarotonAPIKey_Call) Return(s string, err error) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIServerSettingsService_GetExarotonAPIKey_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockIServerSettingsService_GetExarotonAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetExarotonServerInfo provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) GetExarotonServerInfo(ctx context.Context, serverIdx uint) (*dto.ExarotonServerInfo, error) {
	ret := _mock.Called(ctx, serverIdx)

	if len(ret) == 0 {
		panic("no return value specified for GetExarotonServerInfo")
	}

	var r0 *dto.ExarotonServerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*dto.ExarotonServerInfo, error)); ok {
		return returnFunc(ctx, serverIdx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *dto.ExarotonServerInfo); ok {
		r0 = returnFunc(ctx, serverIdx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExarotonServerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, serverIdx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServerSettingsService_GetExarotonServerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExarotonServerInfo'
type MockIServerSettingsService_GetExarotonServerInfo_Call struct {
	*mock.Call
}

// GetExarotonServerInfo is a helper method to define mock.On call
//   - ctx
//   - serverIdx
func (_e *MockIServerSettingsService_Expecter) GetExarotonServerInfo(ctx interface{}, serverIdx interface{}) *MockIServerSettingsService_GetExarotonServerInfo_Call {
	return &MockIServerSettingsService_GetExarotonServerInfo_Call{Call: _e.mock.On("GetExarotonServerInfo", ctx, serverIdx)}
}

func (_c *MockIServerSettingsService_GetExarotonServerInfo_Call) Run(run func(ctx context.Context, serverIdx uint)) *MockIServerSettingsService_GetExarotonServerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIServerSettingsService_GetExarotonServerInfo_Call) Return(exarotonServerInfo *dto.ExarotonServerInfo, err error) *MockIServerSettingsService_GetExarotonServerInfo_Call {
	_c.Call.Return(exarotonServerInfo, err)
	return _c
}

func (_c *MockIServerSettingsService_GetExarotonServerInfo_Call) RunAndReturn(run func(ctx context.Context, serverIdx uint) (*dto.ExarotonServerInfo, error)) *MockIServerSettingsService_GetExarotonServerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ListExarotonServer provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) ListExarotonServer(ctx context.Context) ([]*dto.ExarotonServerInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListExarotonServer")
	}

	var r0 []*dto.ExarotonServerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*dto.ExarotonServerInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*dto.ExarotonServerInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ExarotonServerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServerSettingsService_ListExarotonServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExarotonServer'
type MockIServerSettingsService_ListExarotonServer_Call struct {
	*mock.Call
}

// ListExarotonServer is a helper method to define mock.On call
//   - ctx
func (_e *MockIServerSettingsService_Expecter) ListExarotonServer(ctx interface{}) *MockIServerSettingsService_ListExarotonServer_Call {
	return &MockIServerSettingsService_ListExarotonServer_Call{Call: _e.mock.On("ListExarotonServer", ctx)}
}

func (_c *MockIServerSettingsService_ListExarotonServer_Call) Run(run func(ctx context.Context)) *MockIServerSettingsService_ListExarotonServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIServerSettingsService_ListExarotonServer_Call) Return(exarotonServerInfos []*dto.ExarotonServerInfo, err error) *MockIServerSettingsService_ListExarotonServer_Call {
	_c.Call.Return(exarotonServerInfos, err)
	return _c
}

func (_c *MockIServerSettingsService_ListExarotonServer_Call) RunAndReturn(run func(ctx context.Context) ([]*dto.ExarotonServerInfo, error)) *MockIServerSettingsService_ListExarotonServer_Call {
	_c.Call.Return(run)
	return _c
}

// StartExarotonServer provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) StartExarotonServer(ctx context.Context, serverIdx uint, opts ...service.StartExarotonServerOption) *dto.StartExarotonServerRes {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, serverIdx, opts)
	} else {
		tmpRet = _mock.Called(ctx, serverIdx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for StartExarotonServer")
	}

	var r0 *dto.StartExarotonServerRes
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, ...service.StartExarotonServerOption) *dto.StartExarotonServerRes); ok {
		r0 = returnFunc(ctx, serverIdx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StartExarotonServerRes)
		}
	}
	return r0
}

// MockIServerSettingsService_StartExarotonServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartExarotonServer'
type MockIServerSettingsService_StartExarotonServer_Call struct {
	*mock.Call
}

// StartExarotonServer is a helper method to define mock.On call
//   - ctx
//   - serverIdx
//   - opts
func (_e *MockIServerSettingsService_Expecter) StartExarotonServer(ctx interface{}, serverIdx interface{}, opts ...interface{}) *MockIServerSettingsService_StartExarotonServer_Call {
	return &MockIServerSettingsService_StartExarotonServer_Call{Call: _e.mock.On("StartExarotonServer",
		append([]interface{}{ctx, serverIdx}, opts...)...)}
}

func (_c *MockIServerSettingsService_StartExarotonServer_Call) Run(run func(ctx context.Context, serverIdx uint, opts ...service.StartExarotonServerOption)) *MockIServerSettingsService_StartExarotonServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]service.StartExarotonServerOption)
		run(args[0].(context.Context), args[1].(uint), variadicArgs...)
	})
	return _c
}

func (_c *MockIServerSettingsService_StartExarotonServer_Call) Return(startExarotonServerRes *dto.StartExarotonServerRes) *MockIServerSettingsService_StartExarotonServer_Call {
	_c.Call.Return(startExarotonServerRes)
	return _c
}

func (_c *MockIServerSettingsService_StartExarotonServer_Call) RunAndReturn(run func(ctx context.Context, serverIdx uint, opts ...service.StartExarotonServerOption) *dto.StartExarotonServerRes) *MockIServerSettingsService_StartExarotonServer_Call {
	_c.Call.Return(run)
	return _c
}

// StopExarotonServer provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) StopExarotonServer(ctx context.Context, serverIdx uint) error {
	ret := _mock.Called(ctx, serverIdx)

	if len(ret) == 0 {
		panic("no return value specified for StopExarotonServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, serverIdx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServerSettingsService_StopExarotonServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopExarotonServer'
type MockIServerSettingsService_StopExarotonServer_Call struct {
	*mock.Call
}

// StopExarotonServer is a helper method to define mock.On call
//   - ctx
//   - serverIdx
func (_e *MockIServerSettingsService_Expecter) StopExarotonServer(ctx interface{}, serverIdx interface{}) *MockIServerSettingsService_StopExarotonServer_Call {
	return &MockIServerSettingsService_StopExarotonServer_Call{Call: _e.mock.On("StopExarotonServer", ctx, serverIdx)}
}

func (_c *MockIServerSettingsService_StopExarotonServer_Call) Run(run func(ctx context.Context, serverIdx uint)) *MockIServerSettingsService_StopExarotonServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIServerSettingsService_StopExarotonServer_Call) Return(err error) *MockIServerSettingsService_StopExarotonServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServerSettingsService_StopExarotonServer_Call) RunAndReturn(run func(ctx context.Context, serverIdx uint) error) *MockIServerSettingsService_StopExarotonServer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExarotonAPIKey provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) UpdateExarotonAPIKey(ctx context.Context, apiKey string) error {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExarotonAPIKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServerSettingsService_UpdateExarotonAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExarotonAPIKey'
type MockIServerSettingsService_UpdateExarotonAPIKey_Call struct {
	*mock.Call
}

// UpdateExarotonAPIKey is a helper method to define mock.On call
//   - ctx
//   - apiKey
func (_e *MockIServerSettingsService_Expecter) UpdateExarotonAPIKey(ctx interface{}, apiKey interface{}) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	return &MockIServerSettingsService_UpdateExarotonAPIKey_Call{Call: _e.mock.On("UpdateExarotonAPIKey", ctx, apiKey)}
}

func (_c *MockIServerSettingsService_UpdateExarotonAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIServerSettingsService_UpdateExarotonAPIKey_Call) Return(err error) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServerSettingsService_UpdateExarotonAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) error) *MockIServerSettingsService_UpdateExarotonAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateExarotonAPIKey provides a mock function for the type MockIServerSettingsService
func (_mock *MockIServerSettingsService) ValidateExarotonAPIKey(ctx context.Context, apiKey string) (*dto.ExarotonAccountInfo, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for ValidateExarotonAPIKey")
	}

	var r0 *dto.ExarotonAccountInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.ExarotonAccountInfo, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.ExarotonAccountInfo); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExarotonAccountInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServerSettingsService_ValidateExarotonAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateExarotonAPIKey'
type MockIServerSettingsService_ValidateExarotonAPIKey_Call struct {
	*mock.Call
}

// ValidateExarotonAPIKey is a helper method to define mock.On call
//   - ctx
//   - apiKey
func (_e *MockIServerSettingsService_Expecter) ValidateExarotonAPIKey(ctx interface{}, apiKey interface{}) *MockIServerSettingsService_ValidateExarotonAPIKey_Call {
	return &MockIServerSettingsService_ValidateExarotonAPIKey_Call{Call: _e.mock.On("ValidateExarotonAPIKey", ctx, apiKey)}
}

func (_c *MockIServerSettingsService_ValidateExarotonAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockIServerSettingsService_ValidateExarotonAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIServerSettingsService_ValidateExarotonAPIKey_Call) Return(exarotonAccountInfo *dto.ExarotonAccountInfo, err error) *MockIServerSettingsService_ValidateExarotonAPIKey_Call {
	_c.Call.Return(exarotonAccountInfo, err)
	return _c
}

func (_c *MockIServerSettingsService_ValidateExarotonAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) (*dto.ExarotonAccountInfo, error)) *MockIServerSettingsService_ValidateExarotonAPIKey_Call {
	_c.Call.Return(run)
	return _c
}
