// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"exaroton-wa-bot/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIWhatsappService creates a new instance of MockIWhatsappService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWhatsappService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWhatsappService {
	mock := &MockIWhatsappService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIWhatsappService is an autogenerated mock type for the IWhatsappService type
type MockIWhatsappService struct {
	mock.Mock
}

type MockIWhatsappService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWhatsappService) EXPECT() *MockIWhatsappService_Expecter {
	return &MockIWhatsappService_Expecter{mock: &_m.Mock}
}

// WhitelistGroup provides a mock function for the type MockIWhatsappService
func (_mock *MockIWhatsappService) WhitelistGroup(ctx context.Context, req *dto.WhitelistWhatsappGroupReq) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for WhitelistGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.WhitelistWhatsappGroupReq) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIWhatsappService_WhitelistGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhitelistGroup'
type MockIWhatsappService_WhitelistGroup_Call struct {
	*mock.Call
}

// WhitelistGroup is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockIWhatsappService_Expecter) WhitelistGroup(ctx interface{}, req interface{}) *MockIWhatsappService_WhitelistGroup_Call {
	return &MockIWhatsappService_WhitelistGroup_Call{Call: _e.mock.On("WhitelistGroup", ctx, req)}
}

func (_c *MockIWhatsappService_WhitelistGroup_Call) Run(run func(ctx context.Context, req *dto.WhitelistWhatsappGroupReq)) *MockIWhatsappService_WhitelistGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.WhitelistWhatsappGroupReq))
	})
	return _c
}

func (_c *MockIWhatsappService_WhitelistGroup_Call) Return(err error) *MockIWhatsappService_WhitelistGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIWhatsappService_WhitelistGroup_Call) RunAndReturn(run func(ctx context.Context, req *dto.WhitelistWhatsappGroupReq) error) *MockIWhatsappService_WhitelistGroup_Call {
	_c.Call.Return(run)
	return _c
}
