// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"exaroton-wa-bot/internal/database/entity"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockIUserRepo creates a new instance of MockIUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepo {
	mock := &MockIUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepo is an autogenerated mock type for the IUserRepo type
type MockIUserRepo struct {
	mock.Mock
}

type MockIUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepo) EXPECT() *MockIUserRepo_Expecter {
	return &MockIUserRepo_Expecter{mock: &_m.Mock}
}

// GetUserByUsername provides a mock function for the type MockIUserRepo
func (_mock *MockIUserRepo) GetUserByUsername(ctx context.Context, tx *gorm.DB, username string) (*entity.User, error) {
	ret := _mock.Called(ctx, tx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.User, error)); ok {
		return returnFunc(ctx, tx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.User); ok {
		r0 = returnFunc(ctx, tx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = returnFunc(ctx, tx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepo_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockIUserRepo_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx
//   - tx
//   - username
func (_e *MockIUserRepo_Expecter) GetUserByUsername(ctx interface{}, tx interface{}, username interface{}) *MockIUserRepo_GetUserByUsername_Call {
	return &MockIUserRepo_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, tx, username)}
}

func (_c *MockIUserRepo_GetUserByUsername_Call) Run(run func(ctx context.Context, tx *gorm.DB, username string)) *MockIUserRepo_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(string))
	})
	return _c
}

func (_c *MockIUserRepo_GetUserByUsername_Call) Return(user *entity.User, err error) *MockIUserRepo_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepo_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, username string) (*entity.User, error)) *MockIUserRepo_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}
