// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"exaroton-wa-bot/internal/database/entity"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockIServerSettingsRepo creates a new instance of MockIServerSettingsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIServerSettingsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIServerSettingsRepo {
	mock := &MockIServerSettingsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIServerSettingsRepo is an autogenerated mock type for the IServerSettingsRepo type
type MockIServerSettingsRepo struct {
	mock.Mock
}

type MockIServerSettingsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIServerSettingsRepo) EXPECT() *MockIServerSettingsRepo_Expecter {
	return &MockIServerSettingsRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockIServerSettingsRepo
func (_mock *MockIServerSettingsRepo) Get(ctx context.Context, tx *gorm.DB, key string) (*entity.ServerSettings, error) {
	ret := _mock.Called(ctx, tx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.ServerSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.ServerSettings, error)); ok {
		return returnFunc(ctx, tx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.ServerSettings); ok {
		r0 = returnFunc(ctx, tx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ServerSettings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = returnFunc(ctx, tx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIServerSettingsRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIServerSettingsRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - tx
//   - key
func (_e *MockIServerSettingsRepo_Expecter) Get(ctx interface{}, tx interface{}, key interface{}) *MockIServerSettingsRepo_Get_Call {
	return &MockIServerSettingsRepo_Get_Call{Call: _e.mock.On("Get", ctx, tx, key)}
}

func (_c *MockIServerSettingsRepo_Get_Call) Run(run func(ctx context.Context, tx *gorm.DB, key string)) *MockIServerSettingsRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(string))
	})
	return _c
}

func (_c *MockIServerSettingsRepo_Get_Call) Return(serverSettings *entity.ServerSettings, err error) *MockIServerSettingsRepo_Get_Call {
	_c.Call.Return(serverSettings, err)
	return _c
}

func (_c *MockIServerSettingsRepo_Get_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, key string) (*entity.ServerSettings, error)) *MockIServerSettingsRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockIServerSettingsRepo
func (_mock *MockIServerSettingsRepo) Upsert(ctx context.Context, tx *gorm.DB, settings *entity.ServerSettings) error {
	ret := _mock.Called(ctx, tx, settings)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.ServerSettings) error); ok {
		r0 = returnFunc(ctx, tx, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIServerSettingsRepo_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockIServerSettingsRepo_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx
//   - tx
//   - settings
func (_e *MockIServerSettingsRepo_Expecter) Upsert(ctx interface{}, tx interface{}, settings interface{}) *MockIServerSettingsRepo_Upsert_Call {
	return &MockIServerSettingsRepo_Upsert_Call{Call: _e.mock.On("Upsert", ctx, tx, settings)}
}

func (_c *MockIServerSettingsRepo_Upsert_Call) Run(run func(ctx context.Context, tx *gorm.DB, settings *entity.ServerSettings)) *MockIServerSettingsRepo_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(*entity.ServerSettings))
	})
	return _c
}

func (_c *MockIServerSettingsRepo_Upsert_Call) Return(err error) *MockIServerSettingsRepo_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIServerSettingsRepo_Upsert_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, settings *entity.ServerSettings) error) *MockIServerSettingsRepo_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
