// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockSqlTx creates a new instance of MockSqlTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSqlTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSqlTx {
	mock := &MockSqlTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSqlTx is an autogenerated mock type for the SqlTx type
type MockSqlTx struct {
	mock.Mock
}

type MockSqlTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSqlTx) EXPECT() *MockSqlTx_Expecter {
	return &MockSqlTx_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockSqlTx
func (_mock *MockSqlTx) Begin(ctx context.Context) *gorm.DB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockSqlTx_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockSqlTx_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx
func (_e *MockSqlTx_Expecter) Begin(ctx interface{}) *MockSqlTx_Begin_Call {
	return &MockSqlTx_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockSqlTx_Begin_Call) Run(run func(ctx context.Context)) *MockSqlTx_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSqlTx_Begin_Call) Return(dB *gorm.DB) *MockSqlTx_Begin_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockSqlTx_Begin_Call) RunAndReturn(run func(ctx context.Context) *gorm.DB) *MockSqlTx_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockSqlTx
func (_mock *MockSqlTx) Commit(tx *gorm.DB) error {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = returnFunc(tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqlTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockSqlTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - tx
func (_e *MockSqlTx_Expecter) Commit(tx interface{}) *MockSqlTx_Commit_Call {
	return &MockSqlTx_Commit_Call{Call: _e.mock.On("Commit", tx)}
}

func (_c *MockSqlTx_Commit_Call) Run(run func(tx *gorm.DB)) *MockSqlTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockSqlTx_Commit_Call) Return(err error) *MockSqlTx_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqlTx_Commit_Call) RunAndReturn(run func(tx *gorm.DB) error) *MockSqlTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockSqlTx
func (_mock *MockSqlTx) Rollback(tx *gorm.DB) error {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) error); ok {
		r0 = returnFunc(tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqlTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockSqlTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - tx
func (_e *MockSqlTx_Expecter) Rollback(tx interface{}) *MockSqlTx_Rollback_Call {
	return &MockSqlTx_Rollback_Call{Call: _e.mock.On("Rollback", tx)}
}

func (_c *MockSqlTx_Rollback_Call) Run(run func(tx *gorm.DB)) *MockSqlTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockSqlTx_Rollback_Call) Return(err error) *MockSqlTx_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqlTx_Rollback_Call) RunAndReturn(run func(tx *gorm.DB) error) *MockSqlTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
