// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"exaroton-wa-bot/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIExarotonRepo creates a new instance of MockIExarotonRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIExarotonRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIExarotonRepo {
	mock := &MockIExarotonRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIExarotonRepo is an autogenerated mock type for the IExarotonRepo type
type MockIExarotonRepo struct {
	mock.Mock
}

type MockIExarotonRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIExarotonRepo) EXPECT() *MockIExarotonRepo_Expecter {
	return &MockIExarotonRepo_Expecter{mock: &_m.Mock}
}

// GetServerInfo provides a mock function for the type MockIExarotonRepo
func (_mock *MockIExarotonRepo) GetServerInfo(ctx context.Context, apiKey string, serverID string) (*dto.ExarotonServerInfo, error) {
	ret := _mock.Called(ctx, apiKey, serverID)

	if len(ret) == 0 {
		panic("no return value specified for GetServerInfo")
	}

	var r0 *dto.ExarotonServerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*dto.ExarotonServerInfo, error)); ok {
		return returnFunc(ctx, apiKey, serverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *dto.ExarotonServerInfo); ok {
		r0 = returnFunc(ctx, apiKey, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExarotonServerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, apiKey, serverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIExarotonRepo_GetServerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerInfo'
type MockIExarotonRepo_GetServerInfo_Call struct {
	*mock.Call
}

// GetServerInfo is a helper method to define mock.On call
//   - ctx
//   - apiKey
//   - serverID
func (_e *MockIExarotonRepo_Expecter) GetServerInfo(ctx interface{}, apiKey interface{}, serverID interface{}) *MockIExarotonRepo_GetServerInfo_Call {
	return &MockIExarotonRepo_GetServerInfo_Call{Call: _e.mock.On("GetServerInfo", ctx, apiKey, serverID)}
}

func (_c *MockIExarotonRepo_GetServerInfo_Call) Run(run func(ctx context.Context, apiKey string, serverID string)) *MockIExarotonRepo_GetServerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIExarotonRepo_GetServerInfo_Call) Return(exarotonServerInfo *dto.ExarotonServerInfo, err error) *MockIExarotonRepo_GetServerInfo_Call {
	_c.Call.Return(exarotonServerInfo, err)
	return _c
}

func (_c *MockIExarotonRepo_GetServerInfo_Call) RunAndReturn(run func(ctx context.Context, apiKey string, serverID string) (*dto.ExarotonServerInfo, error)) *MockIExarotonRepo_GetServerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerPlayerList provides a mock function for the type MockIExarotonRepo
func (_mock *MockIExarotonRepo) GetServerPlayerList(ctx context.Context, apiKey string, serverID string) (*dto.ExarotonServerPlayers, error) {
	ret := _mock.Called(ctx, apiKey, serverID)

	if len(ret) == 0 {
		panic("no return value specified for GetServerPlayerList")
	}

	var r0 *dto.ExarotonServerPlayers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*dto.ExarotonServerPlayers, error)); ok {
		return returnFunc(ctx, apiKey, serverID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *dto.ExarotonServerPlayers); ok {
		r0 = returnFunc(ctx, apiKey, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExarotonServerPlayers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, apiKey, serverID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIExarotonRepo_GetServerPlayerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerPlayerList'
type MockIExarotonRepo_GetServerPlayerList_Call struct {
	*mock.Call
}

// GetServerPlayerList is a helper method to define mock.On call
//   - ctx
//   - apiKey
//   - serverID
func (_e *MockIExarotonRepo_Expecter) GetServerPlayerList(ctx interface{}, apiKey interface{}, serverID interface{}) *MockIExarotonRepo_GetServerPlayerList_Call {
	return &MockIExarotonRepo_GetServerPlayerList_Call{Call: _e.mock.On("GetServerPlayerList", ctx, apiKey, serverID)}
}

func (_c *MockIExarotonRepo_GetServerPlayerList_Call) Run(run func(ctx context.Context, apiKey string, serverID string)) *MockIExarotonRepo_GetServerPlayerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIExarotonRepo_GetServerPlayerList_Call) Return(exarotonServerPlayers *dto.ExarotonServerPlayers, err error) *MockIExarotonRepo_GetServerPlayerList_Call {
	_c.Call.Return(exarotonServerPlayers, err)
	return _c
}

func (_c *MockIExarotonRepo_GetServerPlayerList_Call) RunAndReturn(run func(ctx context.Context, apiKey string, serverID string) (*dto.ExarotonServerPlayers, error)) *MockIExarotonRepo_GetServerPlayerList_Call {
	_c.Call.Return(run)
	return _c
}

// ListServers provides a mock function for the type MockIExarotonRepo
func (_mock *MockIExarotonRepo) ListServers(ctx context.Context, apiKey string) ([]*dto.ExarotonServerInfo, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for ListServers")
	}

	var r0 []*dto.ExarotonServerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*dto.ExarotonServerInfo, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*dto.ExarotonServerInfo); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ExarotonServerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIExarotonRepo_ListServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServers'
type MockIExarotonRepo_ListServers_Call struct {
	*mock.Call
}

// ListServers is a helper method to define mock.On call
//   - ctx
//   - apiKey
func (_e *MockIExarotonRepo_Expecter) ListServers(ctx interface{}, apiKey interface{}) *MockIExarotonRepo_ListServers_Call {
	return &MockIExarotonRepo_ListServers_Call{Call: _e.mock.On("ListServers", ctx, apiKey)}
}

func (_c *MockIExarotonRepo_ListServers_Call) Run(run func(ctx context.Context, apiKey string)) *MockIExarotonRepo_ListServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIExarotonRepo_ListServers_Call) Return(exarotonServerInfos []*dto.ExarotonServerInfo, err error) *MockIExarotonRepo_ListServers_Call {
	_c.Call.Return(exarotonServerInfos, err)
	return _c
}

func (_c *MockIExarotonRepo_ListServers_Call) RunAndReturn(run func(ctx context.Context, apiKey string) ([]*dto.ExarotonServerInfo, error)) *MockIExarotonRepo_ListServers_Call {
	_c.Call.Return(run)
	return _c
}

// StartServer provides a mock function for the type MockIExarotonRepo
func (_mock *MockIExarotonRepo) StartServer(ctx context.Context, apiKey string, serverID string, opt dto.StartExarotonServerReq) error {
	ret := _mock.Called(ctx, apiKey, serverID, opt)

	if len(ret) == 0 {
		panic("no return value specified for StartServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dto.StartExarotonServerReq) error); ok {
		r0 = returnFunc(ctx, apiKey, serverID, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIExarotonRepo_StartServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartServer'
type MockIExarotonRepo_StartServer_Call struct {
	*mock.Call
}

// StartServer is a helper method to define mock.On call
//   - ctx
//   - apiKey
//   - serverID
//   - opt
func (_e *MockIExarotonRepo_Expecter) StartServer(ctx interface{}, apiKey interface{}, serverID interface{}, opt interface{}) *MockIExarotonRepo_StartServer_Call {
	return &MockIExarotonRepo_StartServer_Call{Call: _e.mock.On("StartServer", ctx, apiKey, serverID, opt)}
}

func (_c *MockIExarotonRepo_StartServer_Call) Run(run func(ctx context.Context, apiKey string, serverID string, opt dto.StartExarotonServerReq)) *MockIExarotonRepo_StartServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(dto.StartExarotonServerReq))
	})
	return _c
}

func (_c *MockIExarotonRepo_StartServer_Call) Return(err error) *MockIExarotonRepo_StartServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIExarotonRepo_StartServer_Call) RunAndReturn(run func(ctx context.Context, apiKey string, serverID string, opt dto.StartExarotonServerReq) error) *MockIExarotonRepo_StartServer_Call {
	_c.Call.Return(run)
	return _c
}

// StopServer provides a mock function for the type MockIExarotonRepo
func (_mock *MockIExarotonRepo) StopServer(ctx context.Context, apiKey string, serverID string) error {
	ret := _mock.Called(ctx, apiKey, serverID)

	if len(ret) == 0 {
		panic("no return value specified for StopServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, apiKey, serverID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIExarotonRepo_StopServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopServer'
type MockIExarotonRepo_StopServer_Call struct {
	*mock.Call
}

// StopServer is a helper method to define mock.On call
//   - ctx
//   - apiKey
//   - serverID
func (_e *MockIExarotonRepo_Expecter) StopServer(ctx interface{}, apiKey interface{}, serverID interface{}) *MockIExarotonRepo_StopServer_Call {
	return &MockIExarotonRepo_StopServer_Call{Call: _e.mock.On("StopServer", ctx, apiKey, serverID)}
}

func (_c *MockIExarotonRepo_StopServer_Call) Run(run func(ctx context.Context, apiKey string, serverID string)) *MockIExarotonRepo_StopServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIExarotonRepo_StopServer_Call) Return(err error) *MockIExarotonRepo_StopServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIExarotonRepo_StopServer_Call) RunAndReturn(run func(ctx context.Context, apiKey string, serverID string) error) *MockIExarotonRepo_StopServer_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateApiKey provides a mock function for the type MockIExarotonRepo
func (_mock *MockIExarotonRepo) ValidateApiKey(ctx context.Context, apiKey string) (*dto.ExarotonAccountInfo, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for ValidateApiKey")
	}

	var r0 *dto.ExarotonAccountInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.ExarotonAccountInfo, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.ExarotonAccountInfo); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExarotonAccountInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIExarotonRepo_ValidateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateApiKey'
type MockIExarotonRepo_ValidateApiKey_Call struct {
	*mock.Call
}

// ValidateApiKey is a helper method to define mock.On call
//   - ctx
//   - apiKey
func (_e *MockIExarotonRepo_Expecter) ValidateApiKey(ctx interface{}, apiKey interface{}) *MockIExarotonRepo_ValidateApiKey_Call {
	return &MockIExarotonRepo_ValidateApiKey_Call{Call: _e.mock.On("ValidateApiKey", ctx, apiKey)}
}

func (_c *MockIExarotonRepo_ValidateApiKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockIExarotonRepo_ValidateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIExarotonRepo_ValidateApiKey_Call) Return(exarotonAccountInfo *dto.ExarotonAccountInfo, err error) *MockIExarotonRepo_ValidateApiKey_Call {
	_c.Call.Return(exarotonAccountInfo, err)
	return _c
}

func (_c *MockIExarotonRepo_ValidateApiKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) (*dto.ExarotonAccountInfo, error)) *MockIExarotonRepo_ValidateApiKey_Call {
	_c.Call.Return(run)
	return _c
}
