// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package command

import (
	"context"
	"exaroton-wa-bot/internal/service/command"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommand creates a new instance of MockCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommand {
	mock := &MockCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommand is an autogenerated mock type for the Command type
type MockCommand struct {
	mock.Mock
}

type MockCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommand) EXPECT() *MockCommand_Expecter {
	return &MockCommand_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCommand
func (_mock *MockCommand) Execute(c context.Context, args []string) command.CommandResult {
	ret := _mock.Called(c, args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 command.CommandResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) command.CommandResult); ok {
		r0 = returnFunc(c, args)
	} else {
		r0 = ret.Get(0).(command.CommandResult)
	}
	return r0
}

// MockCommand_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommand_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - c
//   - args
func (_e *MockCommand_Expecter) Execute(c interface{}, args interface{}) *MockCommand_Execute_Call {
	return &MockCommand_Execute_Call{Call: _e.mock.On("Execute", c, args)}
}

func (_c *MockCommand_Execute_Call) Run(run func(c context.Context, args []string)) *MockCommand_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockCommand_Execute_Call) Return(commandResult command.CommandResult) *MockCommand_Execute_Call {
	_c.Call.Return(commandResult)
	return _c
}

func (_c *MockCommand_Execute_Call) RunAndReturn(run func(c context.Context, args []string) command.CommandResult) *MockCommand_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Help provides a mock function for the type MockCommand
func (_mock *MockCommand) Help() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Help")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommand_Help_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Help'
type MockCommand_Help_Call struct {
	*mock.Call
}

// Help is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Help() *MockCommand_Help_Call {
	return &MockCommand_Help_Call{Call: _e.mock.On("Help")}
}

func (_c *MockCommand_Help_Call) Run(run func()) *MockCommand_Help_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Help_Call) Return(s string) *MockCommand_Help_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommand_Help_Call) RunAndReturn(run func() string) *MockCommand_Help_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockCommand
func (_mock *MockCommand) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommand_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockCommand_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Name() *MockCommand_Name_Call {
	return &MockCommand_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockCommand_Name_Call) Run(run func()) *MockCommand_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Name_Call) Return(s string) *MockCommand_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommand_Name_Call) RunAndReturn(run func() string) *MockCommand_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockCommand
func (_mock *MockCommand) Usage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommand_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockCommand_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Usage() *MockCommand_Usage_Call {
	return &MockCommand_Usage_Call{Call: _e.mock.On("Usage")}
}

func (_c *MockCommand_Usage_Call) Run(run func()) *MockCommand_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Usage_Call) Return(s string) *MockCommand_Usage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommand_Usage_Call) RunAndReturn(run func() string) *MockCommand_Usage_Call {
	_c.Call.Return(run)
	return _c
}
