// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dto

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMappable creates a new instance of MockMappable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMappable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMappable {
	mock := &MockMappable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMappable is an autogenerated mock type for the Mappable type
type MockMappable struct {
	mock.Mock
}

type MockMappable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMappable) EXPECT() *MockMappable_Expecter {
	return &MockMappable_Expecter{mock: &_m.Mock}
}

// ToMap provides a mock function for the type MockMappable
func (_mock *MockMappable) ToMap() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToMap")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockMappable_ToMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToMap'
type MockMappable_ToMap_Call struct {
	*mock.Call
}

// ToMap is a helper method to define mock.On call
func (_e *MockMappable_Expecter) ToMap() *MockMappable_ToMap_Call {
	return &MockMappable_ToMap_Call{Call: _e.mock.On("ToMap")}
}

func (_c *MockMappable_ToMap_Call) Run(run func()) *MockMappable_ToMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMappable_ToMap_Call) Return(stringToString map[string]string) *MockMappable_ToMap_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockMappable_ToMap_Call) RunAndReturn(run func() map[string]string) *MockMappable_ToMap_Call {
	_c.Call.Return(run)
	return _c
}
